Hides extra map elements
CodeForPhilly/clean-and-green-philly pull request #1060
Opened 2024-12-18 21:13 UTC by DonovanAndrews300

## **Description**
This PR removes the map scale on the bottom left of the property map and hides the map attribute on the bottom right of the map by default.  Addresses [(Issue#1022)](https://github.com/CodeForPhilly/clean-and-green-philly/issues/1022#issuecomment-2543404412) 

---

## **Steps to Test**

1. Navigate to the Property Map
2. You should not see the map scale on the bottom left corner of the map just the map legend
3. The attribution on the bottom right should be hidden when the application loads
---

## **Screenshots**
![Screenshot from 2024-12-18 11-23-06](https://github.com/user-attachments/assets/f27b4a7c-be4e-431a-8a3e-ae9358c29636)

2024-12-23 09:47 UTC, nlebovits commented
@CodeWritingCow can we get a PR review?

2024-12-27 21:29 UTC, CodeWritingCow commented on src/components/PropertyMap.tsx
> +            attributionButton.click();
@DonovanAndrews300 TypeScript is throwing an error saying that `click` doesn't exist on `Element`

2024-12-27 21:36 UTC, CodeWritingCow commented
Hi @DonovanAndrews300 I ran your PR's code locally on my computer, and the UI works as expected.

However, GitHub failed to deploy the PR to Vercel's preview environment. I suspect it's due to a minor TypeScript error. TS says `click` doesn't exist on `Element`:

<img width="832" alt="Screen Shot 2024-12-27 at 4 12 00 PM" src="https://github.com/user-attachments/assets/747f7fcd-76c7-48f1-bb9c-917c4944c736" />

The fix should be pretty easy. If we just annotate `attributionButton`'s type as an HTMLElement, then the error goes away:

<img width="657" alt="Screen Shot 2024-12-27 at 4 23 35 PM" src="https://github.com/user-attachments/assets/c52f1c70-d0c1-4833-bb33-8d73c7dda64b" />

2024-12-27 21:37 UTC, CodeWritingCow commented on src/components/PropertyMap.tsx
> +            attributionButton.click();
TypeScript is throwing a type error saying `click` doesn't exist on `attributeButton`

2024-12-27 21:41 UTC, CodeWritingCow requested changes
Hi @DonovanAndrews300 can you add a type annotation for attributionButton? I'll then approve and merge your PR. Thanks!

2024-12-30 23:25 UTC, CodeWritingCow approved these changes
@DonovanAndrews300 PR looks good. Thanks!

2024-12-30 23:25 UTC, merged