Issue 701: cookie banner re-rendering
CodeForPhilly/clean-and-green-philly pull request #704
Opened 2024-06-23 01:19 UTC by JT0Y

#701 

This resolves the cookie banner re-rendering by recording/checking the user's local storage. Ran into some with node and the localhost spitting out an error about using local storage. Thats what the added checks are about: `typeof window !== "undefined" && window.localStorage`

The issue can be recreated by: 
- running localhost
- take action on cookie banner, either accept or decline
- refresh tab, or open new tab and the cookie banner should re-render

<img width="300" alt="Screenshot 2024-06-22 at 7 02 37 PM" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/8365273/cd85c783-447e-47ea-a0b3-13043008f299">
<img width="300" alt="Screenshot 2024-06-22 at 7 02 47 PM" src="https://github.com/CodeForPhilly/clean-and-green-philly/assets/8365273/3004a6fb-46be-4f0d-942f-490890b928a9">

2024-06-23 04:14 UTC, CodeWritingCow requested changes
Hi @JT0Y, thanks for contributing! I tested your code in my local environment. When I accept cookies and then open the site in a new browser tab, the cookie banner no longer appears.

However, our GitHub repo's Frontend PR Checks are failing due to this error: `ReferenceError: localStorage is not defined`. I'm getting the same error in my localhost ... See screenshot below:

![Screen Shot 2024-06-23 at 12 00 31 AM](https://github.com/CodeForPhilly/clean-and-green-philly/assets/7751862/ebd7205d-9c0a-490e-9699-ec73cea9f45a)

Can you update the PR to resolve this? Thanks!

2024-06-23 04:49 UTC, JT0Y commented
> However, our GitHub repo's Frontend PR Checks are failing due to this error: `ReferenceError: localStorage is not defined`. I'm getting the same error in my localhost ... See screenshot below:
> Can you update the PR to resolve this? Thanks!

yes, I came across this issue and was a bit confused on the issue. I am not familiar with SSR and this environment. But I have additional checks that check if this code is running on a client or not. I did some quick googling on this and this seems to be a well documented issue. Please let me know if this is an unusual pattern, as I am new to next.js & SSR, this _does_ feel strange to me. 

I have tested this and am still able to dismiss the banner and not receiving this issue as well:
```
app-index.js:35 Warning: Prop `className` did not match. Server: "md:flex fixed inset-x-0 bottom-0 z-20 justify-between bg-blue-200 p-4 sm:p-6" Client: "hidden"
```

2024-06-24 19:33 UTC, CodeWritingCow commented
@JT0Y I ran the updated PR locally, and the `localStorage` error is no longer appearing.

Your solution looks sound. By checking if `window.localStorage` exists, we can confirm whether the code is running on the client side. Also, React `useEffect` hooks run only on the client side. So when we execute localStorage code inside those hooks, we'll avoid those `undefined` errors. (I'm also new to SSR, so I had to read up a bit on it too.)

Thanks for your work!

2024-06-24 19:33 UTC, CodeWritingCow approved these changes

2024-06-25 00:57 UTC, JT0Y commented
@CodeWritingCow No worries and thanks for double checking!
Do I need to do anything from here? My understanding from the contributing doc is that I just need to wait for a codeowner to merge it into staging and then close this PR?

2024-06-25 02:27 UTC, CodeWritingCow commented
@JT0Y I'll take it from here. Will merge and close this PR!

2024-06-25 02:28 UTC, merged