Update workflow to store and pull streetview images from GCS subdirectory
CodeForPhilly/clean-and-green-philly pull request #894
Opened 2024-09-19 14:28 UTC by nlebovits

To better organize GCS, this PR adds a subdirectory in which to store streerview images, and also updates the front end to pull the images correctly from that directory. Addresses #717 .

2024-09-19 23:22 UTC, CodeWritingCow commented
@nlebovits the "PR Checks Backend" is failing. A formatting or linting issue might be causing this. Can you take a look? Thanks!

<img width="878" alt="Screen Shot 2024-09-19 at 7 19 42 PM" src="https://github.com/user-attachments/assets/80811119-13a4-4be5-87a6-4d06d4131557">
<img width="878" alt="Screen Shot 2024-09-19 at 7 19 54 PM" src="https://github.com/user-attachments/assets/b4521de0-eb92-4ff8-997c-7fb4dde28676">
<img width="878" alt="Screen Shot 2024-09-19 at 7 20 22 PM" src="https://github.com/user-attachments/assets/2dc33ed9-0f91-4c2c-8912-f6843d06e053">

2024-09-19 23:25 UTC, CodeWritingCow requested changes
Hi @nlebovits this PR is running into formatting or linting issues. Can you take a look?

2024-09-19 23:27 UTC, nlebovits commented
@CodeWritingCow yep! on it

2024-09-22 01:48 UTC, zigouras commented on data/src/streetview.py
> +    url = f"http://example.com/metadata/{address}"
This looks like an incorrect url, it used to be maps.googleapis.com

2024-09-22 01:50 UTC, zigouras commented on data/src/streetview.py
> +    if not blob.exists():
This is contrary to comment above.

2024-09-22 01:50 UTC, zigouras commented on data/src/streetview.py
> +def retry_failed_addresses():
has this been tested?

2024-09-22 01:50 UTC, zigouras commented on data/src/streetview.py
> +def process_failed_addresses_sequentially():
has this been tested?

2024-09-22 01:53 UTC, nlebovits commented
@zigouras thanks for the review. there are a number of errors in the code--I took a break from working on it on Thursday but expect to get back to it this week.

2024-09-25 00:24 UTC, nlebovits commented
@CodeWritingCow can you review the front end pieces of this commit and lmk if you see where my code is going wrong and what I can fix. No worries if not--I need to put more time into this one.

2024-11-25 15:21 UTC, closed without merging