Azbl/875 Fix and hyperlink PA horticultural society on homepage.
CodeForPhilly/clean-and-green-philly pull request #905
Opened 2024-09-23 17:08 UTC by AZBL

This request:

1. Changes Pennsylvania Horticulture Society to Pennsylvania Horticultural Society on homepage.
2. Creates a hyperlink for the text Pennsylvania Horticultural Society to https://phsonline.org/

2024-09-23 17:09 UTC, AZBL commented
@bacitracin @CodeWritingCow

2024-09-24 03:45 UTC, CodeWritingCow commented on src/app/(content-pages)/page.tsx
> +                  Pennsylvania Horticultural Society
Add space between "the" and "Pennsylvania."

![Screen Shot 2024-09-23 at 11 44 00 PM](https://github.com/user-attachments/assets/35f88db7-0806-41bd-9a53-cacc85d8526a)

2024-09-24 03:48 UTC, CodeWritingCow requested changes
Hi @AZBL, the society's name has been corrected, and the new link opened correctly. Just add a space between "the" and "Pennsylvania," and I'll approve this PR. Thanks!

2024-09-24 13:51 UTC, AZBL commented
@CodeWritingCow I added the space so hopefully it's good to go.

2024-09-24 17:01 UTC, merged